---
- name: "Apache installation using docker"
  hosts: prod
  become: true
  pre_tasks:
    - name: Install EPEL repo
      package: name=epel-release state=present
      when: ansible_distribution == "CentOS"

    - name: download pip script
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py

    - name: install python-pip
      command: python2.7 /tmp/get-pip.py

    - name: Install docker python
      pip: name=docker-py

    - name: Install git and wget
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - git
      when: ansible_distribution == "CentOS"

  tasks:
    - name: Create website directory if it does not exist for docker volume binding
      file:
        path: /data/webapp/html
        state: directory
        mode: '0755'

    - name: Generate website file from template to host directory
      template:
        src: templates/index.html.j2
        dest: /data/webapp/html/index.html

    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        volumes:
          - "/data/webapp/html:/usr/local/apache2/htdocs/"
