---
- name: Create website directory if it does not exist for docker volume binding
  file:
    path: "{{ web_dir_host_path }}"
    state: directory
    mode: '0755'

- name: Generate website file from template to host directory
  template:
    src: index.html.j2
    dest: "{{ web_dir_host_path }}/index.html"

- name: Create Apache container
  docker_container:
    name: webapp
    image: "{{ apache_docker_image }}"
    ports:
      - "{{ host_port }}:80"
    volumes:
      - "{{ web_dir_host_path }}:/usr/local/apache2/htdocs/"
